<# 
DOWNLOAD MICROSOFT BOOKS 2017
SOURCE: http://bit.ly/MSBOOKSDL17
USO: CRIE UM DIRETÓRIO (EX. MSBOOKSDL17), SALVE ESSE SCRIPT E EXECUTE (enjoy!!)
#>

Invoke-WebRequest http://ligman.me/1IW1oab -OutFile "Introducing Windows Azure for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1Uixtlq -OutFile "Introducing Windows Azure for IT Professionals.mobi"
Invoke-WebRequest http://ligman.me/1R9Ubgt -OutFile "Introducing Windows Azure for IT Professionals.epub"
Invoke-WebRequest http://ligman.me/1H4VXHT -OutFile "Microsoft Azure Essentials Azure Automation.pdf"
Invoke-WebRequest http://ligman.me/1f8XUKy -OutFile "Microsoft Azure Essentials Azure Automation.mobi"
Invoke-WebRequest http://ligman.me/1HBEUPi -OutFile "Microsoft Azure Essentials Azure Automation.epub"
Invoke-WebRequest http://ligman.me/1NDTZR4 -OutFile "Microsoft Azure Essentials Azure Machine Learning.pdf"
Invoke-WebRequest http://ligman.me/1Uiy2f9 -OutFile "Microsoft Azure Essentials Azure Machine Learning.mobi"
Invoke-WebRequest http://ligman.me/1epZ0QU -OutFile "Microsoft Azure Essentials Azure Machine Learning.epub"
Invoke-WebRequest http://ligman.me/1JIhgjA -OutFile "Microsoft Azure Essentials Fundamentals of Azure.pdf"
Invoke-WebRequest http://ligman.me/1CQX5uG -OutFile "Microsoft Azure Essentials Fundamentals of Azure.mobi"
Invoke-WebRequest http://ligman.me/1JD5Q3i -OutFile "Microsoft Azure Essentials Fundamentals of Azure.epub"
Invoke-WebRequest http://ligman.me/2sUanwC -OutFile "Microsoft Azure Essentials Fundamentals of Azure, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/2twPBSD -OutFile "Microsoft Azure Essentials Fundamentals of Azure, Second Edition Mobile.pdf"
Invoke-WebRequest http://ligman.me/2tE7q0i -OutFile "Microsoft Azure Essentials Migrating SQL Server Databases to Azure – Mobile.pdf"
Invoke-WebRequest http://ligman.me/2t2y29a -OutFile "Microsoft Azure Essentials Migrating SQL Server Databases to Azure 8.5X11.pdf"
Invoke-WebRequest http://ligman.me/2tJ1pj4 -OutFile "Microsoft Azure ExpressRoute Guide.pdf"
Invoke-WebRequest http://ligman.me/2u2KdXT -OutFile "Rapid Deployment Guide For Azure Rights Management.pdf"
Invoke-WebRequest http://ligman.me/1IW1s9S -OutFile "Rethinking Enterprise Storage A Hybrid Cloud Model.pdf"
Invoke-WebRequest http://ligman.me/1UixANR -OutFile "Rethinking Enterprise Storage A Hybrid Cloud Model.mobi"
Invoke-WebRequest http://ligman.me/1f8Xvri -OutFile "Rethinking Enterprise Storage A Hybrid Cloud Model.epub"
Invoke-WebRequest http://ligman.me/2tEn8Zy -OutFile "BizTalk Server 2016 Licensing Datasheet.pdf"
Invoke-WebRequest http://ligman.me/2tEbPAp -OutFile "BizTalk Server 2016 Management Pack Guide.doc"
Invoke-WebRequest http://ligman.me/2u0WD2F -OutFile "Enterprise Cloud Strategy.pdf"
Invoke-WebRequest http://ligman.me/2t2FyB9 -OutFile "Enterprise Cloud Strategy.mobi"
Invoke-WebRequest http://ligman.me/2uGi1Ig -OutFile "Enterprise Cloud Strategy.epub"
Invoke-WebRequest http://ligman.me/2t2Ghm1 -OutFile "Enterprise Cloud Strategy – Mobile.pdf"
Invoke-WebRequest http://ligman.me/2sLiBTE -OutFile ".NET Microservices Architecture for Containerized .NET Applications.pdf"
Invoke-WebRequest http://ligman.me/1gfeQ27 -OutFile ".NET Technology Guidance for Business Applications.pdf"
Invoke-WebRequest http://ligman.me/1KBM8DL -OutFile "Building Cloud Apps with Microsoft Azure Best practices for DevOps, data storage, high availability, and more.pdf"
Invoke-WebRequest http://ligman.me/1GVxKR6 -OutFile "Building Cloud Apps with Microsoft Azure Best practices for DevOps, data storage, high availability, and more.mobi"
Invoke-WebRequest http://ligman.me/1KBM1YL -OutFile "Building Cloud Apps with Microsoft Azure Best practices for DevOps, data storage, high availability, and more.epub"
Invoke-WebRequest http://ligman.me/2v7M0bp -OutFile "Containerized Docker Application Lifecycle with Microsoft Platform and Tools.pdf"
Invoke-WebRequest http://ligman.me/1dDcwQC -OutFile "Creating Mobile Apps with Xamarin.Forms, Preview Edition 2.pdf"
Invoke-WebRequest http://ligman.me/1LIQw4D -OutFile "Creating Mobile Apps with Xamarin.Forms, Preview Edition 2.mobi"
Invoke-WebRequest http://ligman.me/1HCWJ2c -OutFile "Creating Mobile Apps with Xamarin.Forms, Preview Edition 2.epub"
Invoke-WebRequest http://ligman.me/2u1190V -OutFile "Creating Mobile Apps with Xamarin.Forms Cross-platform C# programming for iOS, Android, and Windows.pdf"
Invoke-WebRequest http://ligman.me/2sE8dNG -OutFile "Creating Mobile Apps with Xamarin.Forms Cross-platform C# programming for iOS, Android, and Windows.mobi"
Invoke-WebRequest http://ligman.me/2twPKVT -OutFile "Creating Mobile Apps with Xamarin.Forms Cross-platform C# programming for iOS, Android, and Windows.epub"
Invoke-WebRequest http://ligman.me/1NErkvl -OutFile "Managing Agile Open-Source Software Projects with Microsoft Visual Studio Online.pdf"
Invoke-WebRequest http://ligman.me/1KyWplK -OutFile "Managing Agile Open-Source Software Projects with Microsoft Visual Studio Online.mobi"
Invoke-WebRequest http://ligman.me/1RabduO -OutFile "Managing Agile Open-Source Software Projects with Microsoft Visual Studio Online.epub"
Invoke-WebRequest http://ligman.me/1epZeHO -OutFile "Microsoft Azure Essentials Azure Web Apps for Developers.pdf"
Invoke-WebRequest http://ligman.me/2tE9hCx -OutFile "Microsoft Azure Essentials Azure Web Apps for Developers.mobi"
Invoke-WebRequest http://ligman.me/2uFU3wF -OutFile "Microsoft Azure Essentials Azure Web Apps for Developers.epub"
Invoke-WebRequest http://ligman.me/2t2WqaR -OutFile "Microsoft Platform and Tools for Mobile App Development.pdf"
Invoke-WebRequest http://ligman.me/2sUA9kk -OutFile "Microsoft Platform and Tools for Mobile App Development – Mobile.pdf"
Invoke-WebRequest http://ligman.me/1CQXMEp -OutFile "Moving to Microsoft Visual Studio 2010.xps"
Invoke-WebRequest http://ligman.me/1JITgwM -OutFile "Moving to Microsoft Visual Studio 2010.pdf"
Invoke-WebRequest http://ligman.me/1RaaZny -OutFile "Moving to Microsoft Visual Studio 2010.mobi"
Invoke-WebRequest http://ligman.me/2uZg49h -OutFile "Moving to Microsoft Visual Studio 2010.epub"
Invoke-WebRequest http://ligman.me/1LN5APL -OutFile "Programming Windows 8 Apps with HTML, CSS, and JavaScript.pdf"
Invoke-WebRequest http://ligman.me/1GVx0eW -OutFile "Programming Windows 8 Apps with HTML, CSS, and JavaScript.mobi"
Invoke-WebRequest http://ligman.me/1dD5sDy -OutFile "Programming Windows 8 Apps with HTML, CSS, and JavaScript.epub"
Invoke-WebRequest http://ligman.me/1RWzfoe -OutFile "Programming Windows Store Apps with HTML, CSS, and JavaScript, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/1JDj7Jl -OutFile "Programming Windows Store Apps with HTML, CSS, and JavaScript, Second Edition.mobi"
Invoke-WebRequest http://ligman.me/1f9bOfu -OutFile "Programming Windows Store Apps with HTML, CSS, and JavaScript, Second Edition.epub"
Invoke-WebRequest http://ligman.me/1LNdusd -OutFile "Programming Windows Phone 7 (Special Excerpt 2).xps"
Invoke-WebRequest http://ligman.me/1KyWLZv -OutFile "Programming Windows Phone 7 (Special Excerpt 2).pdf"
Invoke-WebRequest http://ligman.me/2tEKIoU -OutFile "Team Foundation Server to Visual Studio Team Services Migration Guide.pdf"
Invoke-WebRequest http://ligman.me/2uGZkV1 -OutFile "5 cool things you can do with CRM for tablets.pdf"
Invoke-WebRequest http://ligman.me/2tJAEuU -OutFile "Create Custom Analytics in Dynamics 365 with Power BI.pdf"
Invoke-WebRequest http://ligman.me/1odT1MW -OutFile "Create of Customize System Dashboards.pdf"
Invoke-WebRequest http://ligman.me/1NJ0vpb -OutFile "Create Your First CRM Marketing Campaign.pdf"
Invoke-WebRequest http://ligman.me/1dHBtdA -OutFile "CRM Basics for Outlook basics.pdf"
Invoke-WebRequest http://ligman.me/1NIYrxw -OutFile "CRM Basics for Sales Pros and Service Reps.pdf"
Invoke-WebRequest http://ligman.me/1qNYIYi -OutFile "Give Great Customer Service with CRM.pdf"
Invoke-WebRequest http://ligman.me/1rH9Ar3 -OutFile "Go Mobile with CRM for Phones – Express.pdf"
Invoke-WebRequest http://ligman.me/1kvWKEm -OutFile "Go Mobile with CRM for Tablets.pdf"
Invoke-WebRequest http://ligman.me/1m8yCMD -OutFile "Import Contacts into CRM.pdf"
Invoke-WebRequest http://ligman.me/1kvXrxj -OutFile "Introducing Microsoft Social Engagement.pdf"
Invoke-WebRequest http://ligman.me/1pUnYfG -OutFile "Introduction to Business Processes.pdf"
Invoke-WebRequest http://ligman.me/1CWgeLI -OutFile "Meet Your Service Goals with SLAs and Entitlements.pdf"
Invoke-WebRequest http://ligman.me/2v0ShWr -OutFile "Microsoft Dynamics CRM 2016 Interactive Service Hub User Guide.pdf"
Invoke-WebRequest http://ligman.me/2sF6M19 -OutFile "Microsoft Dynamics CRM 2016 On-Premises Volume Licensing and Pricing Guide.pdf"
Invoke-WebRequest http://ligman.me/2sVh6qf -OutFile "Microsoft Dynamics CRM for Outlook Installing Guide for use with Microsoft Dynamics CRM Online.pdf"
Invoke-WebRequest http://ligman.me/2tYdqU8 -OutFile "Microsoft Dynamics CRM Resource Guide 2015.pdf"
Invoke-WebRequest http://ligman.me/1oB9ptL -OutFile "Microsoft Social Engagement for CRM.pdf"
Invoke-WebRequest http://ligman.me/2sFbbl0 -OutFile "Product Overview and Capability Guide Microsoft Dynamics NAV 2016.pdf"
Invoke-WebRequest http://ligman.me/2v1ok8u -OutFile "RAP as a Service for Dynamics CRM.pdf"
Invoke-WebRequest http://ligman.me/1HIcIKB -OutFile "Set Up A Social Engagement Search For Your Product.pdf"
Invoke-WebRequest http://ligman.me/1Cl328D -OutFile "Social is for Closers.pdf"
Invoke-WebRequest http://ligman.me/VSpodw -OutFile "Start Working in CRM.pdf"
Invoke-WebRequest http://ligman.me/1S36CGa -OutFile "Your Brand Sux.pdf"
Invoke-WebRequest http://ligman.me/2tEPKBF -OutFile "10 essential tips and tools for mobile working.pdf"
Invoke-WebRequest http://ligman.me/2sVSiyp -OutFile "An employee’s guide to healthy computing.pdf"
Invoke-WebRequest http://ligman.me/2tEHPV9 -OutFile "Guide for People who have Language or Communication Disabilities.doc"
Invoke-WebRequest http://ligman.me/2t3xIav -OutFile "Guide for People who have Learning Disabilities.doc"
Invoke-WebRequest http://ligman.me/1H1MFKr -OutFile "Introduction to Per Core Licensing and Basic Definitions.pdf"
Invoke-WebRequest http://ligman.me/2u2bSbh -OutFile "Licensing Windows and Microsoft Office for use on the Macintosh.pdf"
Invoke-WebRequest http://ligman.me/2u7XYoT -OutFile "VLSC Software Assurance Guide.pdf"
Invoke-WebRequest http://ligman.me/2txAWqi -OutFile "Windows Server 2016 and System Center 2016 Pricing and Licensing FAQs.pdf"
Invoke-WebRequest http://ligman.me/1sgBtn4 -OutFile "Access 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2tEnvmU -OutFile "Azure AD/Office 365 seamless sign-in.pdf"
Invoke-WebRequest http://ligman.me/2txxLic -OutFile "Content Encryption in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2u89sJ3 -OutFile "Controlling Access to Office 365 and Protecting Content on Devices.pdf"
Invoke-WebRequest http://ligman.me/1qzON6Q -OutFile "Customize Word 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2tXYR34 -OutFile "Data Resiliency in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/1onTg9n -OutFile "Excel 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2uH1nrZ -OutFile "Excel 2016 keyboard shortcuts and function keys.doc"
Invoke-WebRequest http://ligman.me/VP2t2L -OutFile "Excel Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2v0u0jd -OutFile "File Protection Solutions in Office 365.pdf"
Invoke-WebRequest http://ligman.me/1dD6v6s -OutFile "First Look Microsoft Office 2010.xps"
Invoke-WebRequest http://ligman.me/1Ra595J -OutFile "First Look Microsoft Office 2010.pdf"
Invoke-WebRequest http://ligman.me/2v0H3ku -OutFile "Get Started With Microsoft OneDrive.pdf"
Invoke-WebRequest http://ligman.me/2tEtms3 -OutFile "Get Started With Microsoft Project Online.pdf"
Invoke-WebRequest http://ligman.me/2u88i06 -OutFile "Getting started with MyAnalytics.doc"
Invoke-WebRequest http://ligman.me/1jWMJA2 -OutFile "How To Recover That Un-Saved Office Document.pdf"
Invoke-WebRequest http://ligman.me/1qZlnOJ -OutFile "InfoPath 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2u2RnLQ -OutFile "Keyboard shortcuts for Microsoft Outlook 2013 and 2016.doc"
Invoke-WebRequest http://ligman.me/2v0AQFy -OutFile "Keyboard shortcuts for Microsoft Word 2016 for Windows.doc"
Invoke-WebRequest http://ligman.me/1xqtaWN -OutFile "Licensing Microsoft Office 365 ProPlus Subscription Service in Volume Licensing.pdf"
Invoke-WebRequest http://ligman.me/2v0v72p -OutFile "Licensing Microsoft Office software in Volume Licensing.pdf"
Invoke-WebRequest http://ligman.me/1HCDxl9 -OutFile "Microsoft Access 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/2u7Lw8N -OutFile "Microsoft Classroom Deployment.pdf"
Invoke-WebRequest http://ligman.me/1HByNKS -OutFile "Microsoft Excel 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29a22WR -OutFile "Microsoft Excel 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29bcJtd -OutFile "Microsoft Excel 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29rwoHw -OutFile "Microsoft Excel Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/2sF7s6H -OutFile "Microsoft Excel VLOOKUP Troubleshooting Tips.pdf"
Invoke-WebRequest http://ligman.me/1CSMobd -OutFile "Microsoft OneNote 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d5XTw -OutFile "Microsoft OneNote 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29rwoY0 -OutFile "Microsoft OneNote 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d1wc3 -OutFile "Microsoft OneNote 2016 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/29fudHc -OutFile "Microsoft OneNote Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1FYtDD8 -OutFile "Microsoft Outlook 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29hVdVa -OutFile "Microsoft Outlook 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDult -OutFile "Microsoft Outlook 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29cfePX -OutFile "Microsoft Outlook 2016 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/1NCfcKC -OutFile "Microsoft Powerpoint 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDylj -OutFile "Microsoft PowerPoint 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDylj -OutFile "Microsoft PowerPoint 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d5AbX -OutFile "Microsoft PowerPoint Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1JI6V77 -OutFile "Microsoft Project 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1H4Q0e5 -OutFile "Microsoft Publisher 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1LMpRns -OutFile "Microsoft Visio 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1HCCCRP -OutFile "Microsoft Word 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29FzGG5 -OutFile "Microsoft Word 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29e6cTO -OutFile "Microsoft Word 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29gfrkN -OutFile "Microsoft Word Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1Ra5c1c -OutFile "Microsoft Office 365 Connect and Collaborate Virtually Anywhere, Anytime.pdf"
Invoke-WebRequest http://ligman.me/29vGIvY -OutFile "Monitoring and protecting sensitive data in Office 365.doc"
Invoke-WebRequest http://ligman.me/2sVGUSX -OutFile "Office 365 Dedicated Platform vNext Service Release.pdf"
Invoke-WebRequest http://ligman.me/2u1KmL9 -OutFile "Office 365 Licensing Brief.pdf"
Invoke-WebRequest http://ligman.me/1n49kzj -OutFile "OneNote 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1qZlFVR -OutFile "OneNote Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/TWa2Dg -OutFile "Outlook 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1xzdEtT -OutFile "Outlook Web App Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1HCQyeA -OutFile "Own Your Future Update Your Skills with Resources and Career Ideas from Microsoft.xps"
Invoke-WebRequest http://ligman.me/1Cg5iOv -OutFile "Own Your Future Update Your Skills with Resources and Career Ideas from Microsoft.pdf"
Invoke-WebRequest http://ligman.me/2sUC4FK -OutFile "Own Your Future Update Your Skills with Resources and Career Ideas from Microsoft.mobi"
Invoke-WebRequest http://ligman.me/2u12ggX -OutFile "Own Your Future Update Your Skills with Resources and Career Ideas from Microsoft.epub"
Invoke-WebRequest http://ligman.me/1onU8Ld -OutFile "PowerPoint Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1vM9mwt -OutFile "Project 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1rB8nl1 -OutFile "Publisher 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1JDjqUt -OutFile "Security and Privacy For Microsoft Office 2010 Users.pdf"
Invoke-WebRequest http://ligman.me/1eqdXCI -OutFile "Security and Privacy For Microsoft Office 2010 Users.mobi"
Invoke-WebRequest http://ligman.me/1Uj0hu2 -OutFile "Security and Privacy For Microsoft Office 2010 Users.epub"
Invoke-WebRequest http://ligman.me/2tYk9gX -OutFile "Security Incident Management in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2tYk9gX -OutFile "Security Incident Management in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2sVrsGy -OutFile "SharePoint Online Dedicated & OneDrive for Business Dedicated vNext Service Release.pdf"
Invoke-WebRequest http://ligman.me/1M7Xr5v -OutFile "Skype for Business User Tips & Tricks for Anyone.pdf"
Invoke-WebRequest http://ligman.me/2t3nqXV -OutFile "Switching from Google Apps to Office 365 for business.pdf"
Invoke-WebRequest http://ligman.me/2u2K9aI -OutFile "Tenant Isolation in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/1vM9H2d -OutFile "Visio 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2sFsnXy -OutFile "Windows 10 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/1m6xucg -OutFile "Word 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1qzRntH -OutFile "Word Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1lJmKeW -OutFile "Working with SmartArt Graphics Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/29ZNaMN -OutFile "Ask, find, and act—harnessing the power of Cortana and Power BI.doc"
Invoke-WebRequest http://ligman.me/2tEERQt -OutFile "Bidirectional cross-filtering in SQL Server Analysis Services 2016 and Power BI Desktop.doc"
Invoke-WebRequest http://ligman.me/29sp3nZ -OutFile "Configuring Power BI mobile apps with Microsoft Intune.doc"
Invoke-WebRequest http://ligman.me/29LXmMt -OutFile "Getting started with the Power BI for Android app.doc"
Invoke-WebRequest http://ligman.me/29EmfZc -OutFile "Getting Started with the Power BI for iOS app.doc"
Invoke-WebRequest http://ligman.me/2t3HOIt -OutFile "How to plan capacity for embedded analytics with Power BI Premium.pdf"
Invoke-WebRequest http://ligman.me/2tE789y -OutFile "Introducing Microsoft Power BI.pdf"
Invoke-WebRequest http://ligman.me/2sUDY9j -OutFile "Introducing Microsoft Power BI – Mobile.pdf"
Invoke-WebRequest http://ligman.me/2tEI5U4 -OutFile "Microsoft Power BI Premium Whitepaper.pdf"
Invoke-WebRequest http://ligman.me/29yWFFf -OutFile "Power BI mobile apps—enabling data analytics on the go.doc"
Invoke-WebRequest http://ligman.me/2tEtGXW -OutFile "Propelling digital transformation in manufacturing operations with Power BI.doc"
Invoke-WebRequest http://ligman.me/2txJKMz -OutFile "Using Power BI to visualize data insights from Microsoft Dynamics CRM Online.doc"
Invoke-WebRequest http://ligman.me/2uH1kN1 -OutFile "Microsoft Dynamics GP 2015 R2 PowerShell Users Guide.pdf"
Invoke-WebRequest http://ligman.me/2tY8L4x -OutFile "PowerShell Integrated Scripting Environment 3.0.pdf"
Invoke-WebRequest http://ligman.me/2tyf2TJ -OutFile "Simplify Group Policy administration with Windows PowerShell.pdf"
Invoke-WebRequest http://ligman.me/2v0CY01 -OutFile "Windows PowerShell – Management of Active Directory Infrastructure.pdf"
Invoke-WebRequest http://ligman.me/2v0vXMn -OutFile "Windows PowerShell 3.0 Examples.pdf"
Invoke-WebRequest http://ligman.me/2u8l13d -OutFile "Windows PowerShell 3.0 Language Quick Reference.pdf"
Invoke-WebRequest http://ligman.me/2u8jZEr -OutFile "WINDOWS POWERSHELL 4.0 LANGUAGE QUICK REFERENCE.pdf"
Invoke-WebRequest http://ligman.me/1omCrM6 -OutFile "Windows PowerShell 4.0 Language Reference Examples.pdf"
Invoke-WebRequest http://ligman.me/2sFvbUs -OutFile "Windows PowerShell Command Builder User’s Guide.pdf"
Invoke-WebRequest http://ligman.me/2tYmSHb -OutFile "Windows PowerShell Desired State Configuration Quick Reference.pdf"
Invoke-WebRequest http://ligman.me/1n3mkVY -OutFile "WINDOWS POWERSHELL INTEGRATED SCRIPTING ENVIRONMENT 4.0.pdf"
Invoke-WebRequest http://ligman.me/2tEXUKw -OutFile "Windows PowerShell Web Access.pdf"
Invoke-WebRequest http://ligman.me/2tEAt3Z -OutFile "WMI in PowerShell 3.0.pdf"
Invoke-WebRequest http://ligman.me/2t3uPGw -OutFile "WMI in Windows PowerShell 4.0.pdf"
Invoke-WebRequest http://ligman.me/2uFTByu -OutFile "Configuring Microsoft SharePoint Hybrid Capabilities.pdf"
Invoke-WebRequest http://ligman.me/2tXvePt -OutFile "Configuring Microsoft SharePoint Hybrid Capabilities – Mobile.pdf"
Invoke-WebRequest http://ligman.me/12FIZ1I -OutFile "Deployment guide for Microsoft SharePoint 2013.pdf"
Invoke-WebRequest http://ligman.me/2v0Dhb1 -OutFile "Microsoft SharePoint Server 2016 Architectural Models.pdf"
Invoke-WebRequest http://ligman.me/2u0QCD2 -OutFile "Planning and Preparing for Microsoft SharePoint Hybrid – 8.5 X 11.pdf"
Invoke-WebRequest http://ligman.me/2sEzMGA -OutFile "Planning and Preparing for Microsoft SharePoint Hybrid – Mobile.pdf"
Invoke-WebRequest http://ligman.me/2u8h5PG -OutFile "RAP as a Service for SharePoint Server.pdf"
Invoke-WebRequest http://ligman.me/2uGN9ao -OutFile "SharePoint Online Dedicated Service Description.pdf"
Invoke-WebRequest http://ligman.me/TL3pn1 -OutFile "SharePoint Products Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2txHeGo -OutFile "SharePoint Server 2016 Databases – Quick Reference Guide.pdf"
Invoke-WebRequest http://ligman.me/29FkNr3 -OutFile "SharePoint Server 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1anyEJj -OutFile "5 Tips For A Smooth SSIS Upgrade to SQL Server 2012.pdf"
Invoke-WebRequest http://ligman.me/N1HEpM -OutFile "Backup and Restore of SQL Server Databases.pdf"
Invoke-WebRequest http://ligman.me/2sVpUwk -OutFile "Data Science with Microsoft SQL Server 2016.pdf"
Invoke-WebRequest http://ligman.me/2u8ao0i -OutFile "Deeper insights across data with SQL Server 2016 – Technical White Paper.pdf"
Invoke-WebRequest http://ligman.me/2u7MT7t -OutFile "Deploying SQL Server 2016 PowerPivot and Power View in a Multi-Tier SharePoint 2016 Farm.doc"
Invoke-WebRequest http://ligman.me/2u89lNQ -OutFile "Deploying SQL Server 2016 PowerPivot and Power View in SharePoint 2016.doc"
Invoke-WebRequest http://ligman.me/1ReR3Qq -OutFile "Guide to Migrating from Oracle to SQL Server 2014 and Azure SQL Database.pdf"
Invoke-WebRequest http://ligman.me/1RWzIGZ -OutFile "Introducing Microsoft Azure HDInsight.pdf"
Invoke-WebRequest http://ligman.me/1CQXzkt -OutFile "Introducing Microsoft Azure HDInsight.mobi"
Invoke-WebRequest http://ligman.me/1HBRMVs -OutFile "Introducing Microsoft Azure HDInsight.epub"
Invoke-WebRequest http://ligman.me/2u2j5sf -OutFile "Introducing Microsoft Data Warehouse Fast Track for SQL Server 2016.pdf"
Invoke-WebRequest http://ligman.me/1gfab07 -OutFile "Introducing Microsoft SQL Server 2012.pdf"
Invoke-WebRequest http://ligman.me/1JIDq58 -OutFile "Introducing Microsoft SQL Server 2012.mobi"
Invoke-WebRequest http://ligman.me/1KBMoTl -OutFile "Introducing Microsoft SQL Server 2012.epub"
Invoke-WebRequest http://ligman.me/1C7dU9J -OutFile "Introducing Microsoft SQL Server 2014.pdf"
Invoke-WebRequest http://ligman.me/1GVycPq -OutFile "Introducing Microsoft SQL Server 2014.mobi"
Invoke-WebRequest http://ligman.me/1LIJflp -OutFile "Introducing Microsoft SQL Server 2014.epub"
Invoke-WebRequest http://ligman.me/2u7ml6r -OutFile "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2.pdf"
Invoke-WebRequest http://ligman.me/2tXqzgh -OutFile "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2.mobi"
Invoke-WebRequest http://ligman.me/2u0ZCYU -OutFile "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2.epub"
Invoke-WebRequest http://ligman.me/2t2o340 -OutFile "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2 – Mobile.pdf"
Invoke-WebRequest http://ligman.me/2txRCxI -OutFile "Introducing Microsoft Technologies for Data Storage, Movement and Transformation.doc"
Invoke-WebRequest http://ligman.me/1CQXzko -OutFile "Introducing Microsoft SQL Server 2008 R2.xps"
Invoke-WebRequest http://ligman.me/1KyNJvs -OutFile "Introducing Microsoft SQL Server 2008 R2.pdf"
Invoke-WebRequest http://ligman.me/1C7dEYi -OutFile "Introducing Microsoft SQL Server 2008 R2.mobi"
Invoke-WebRequest http://ligman.me/1IzBL34 -OutFile "Introducing Microsoft SQL Server 2008 R2.epub"
Invoke-WebRequest http://ligman.me/29pcQFA -OutFile "Microsoft SharePoint Server 2016 Reviewer’s Guide.pdf"
Invoke-WebRequest http://ligman.me/N1J8A8 -OutFile "Microsoft SQL Server 2012 Tutorials Analysis Services – Data Mining Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/N1JfvI -OutFile "Microsoft SQL Server 2012 Tutorials Analysis Services – Multidimensional Modeling Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/16E6G9L -OutFile "Microsoft SQL Server 2012 Tutorials Reporting Services Quick Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/16dHXZ9 -OutFile "Microsoft SQL Server 2012 Tutorials Writing Transact-SQL-Statements.pdf"
Invoke-WebRequest http://ligman.me/1S1f34H -OutFile "Microsoft SQL Server 2014 Licensing Guide.pdf"
Invoke-WebRequest http://ligman.me/2sFqolM -OutFile "Microsoft SQL Server 2016 Licensing Datasheet.pdf"
Invoke-WebRequest http://ligman.me/2tEHwtq -OutFile "Microsoft SQL Server 2016 Licensing Guide.pdf"
Invoke-WebRequest http://ligman.me/2uGQTc7 -OutFile "Microsoft SQL Server 2016 Mission-Critical Performance Technical White Paper.pdf"
Invoke-WebRequest http://ligman.me/2u7TbUy -OutFile "Microsoft SQL Server 2016 New Innovations.pdf"
Invoke-WebRequest http://ligman.me/2tYmEzR -OutFile "Microsoft SQL Server 2016 SP1 Editions.pdf"
Invoke-WebRequest http://ligman.me/2tYaW8d -OutFile "Microsoft SQL Server In-Memory OLTP and Columnstore Feature Comparison.pdf"
Invoke-WebRequest http://ligman.me/2u2HKg6 -OutFile "RAP as a Service for SQL Server.pdf"
Invoke-WebRequest http://ligman.me/2tEHLVm -OutFile "SQLCAT’s Guide to Relational Engine.pdf"
Invoke-WebRequest http://ligman.me/11IMDlh -OutFile "Xquery Language Reference.pdf"
Invoke-WebRequest http://ligman.me/29i2CEe -OutFile "Surface Book User Guide.pdf"
Invoke-WebRequest http://ligman.me/29hofVk -OutFile "Surface Pro 4 User Guide.pdf"
Invoke-WebRequest http://ligman.me/2sVrwWU -OutFile "Guide to Microsoft System Center Management Pack for SQL Server 2016 Reporting Services (Native Mode).doc"
Invoke-WebRequest http://ligman.me/2u2uvvZ -OutFile "Guide to System Center Management Pack for Windows Print Server 2016.doc"
Invoke-WebRequest http://ligman.me/1dD6S0J -OutFile "Introducing Microsoft System Center 2012 R2.pdf"
Invoke-WebRequest http://ligman.me/1NEgrJQ -OutFile "Introducing Microsoft System Center 2012 R2.mobi"
Invoke-WebRequest http://ligman.me/1IzC1z4 -OutFile "Introducing Microsoft System Center 2012 R2.epub"
Invoke-WebRequest http://ligman.me/2sUch05 -OutFile "Microsoft System Center Building a Virtualized Network Solution, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/2twxADW -OutFile "Microsoft System Center Building a Virtualized Network Solution, Second Edition.mobi"
Invoke-WebRequest http://ligman.me/2sEqaM0 -OutFile "Microsoft System Center Building a Virtualized Network Solution, Second Edition.epub"
Invoke-WebRequest http://ligman.me/1JDrhBp -OutFile "Microsoft System Center Data Protection for the Hybrid Cloud.pdf"
Invoke-WebRequest http://ligman.me/1RWFCrK -OutFile "Microsoft System Center Data Protection for the Hybrid Cloud.mobi"
Invoke-WebRequest http://ligman.me/1M05t0d -OutFile "Microsoft System Center Data Protection for the Hybrid Cloud.epub"
Invoke-WebRequest http://ligman.me/1C7okGv -OutFile "Microsoft System Center Deploying Hyper-V with Software-Defined Storage & Networking.pdf"
Invoke-WebRequest http://ligman.me/1UjcLBK -OutFile "Microsoft System Center Deploying Hyper-V with Software-Defined Storage & Networking.mobi"
Invoke-WebRequest http://ligman.me/1HBYNpg -OutFile "Microsoft System Center Deploying Hyper-V with Software-Defined Storage & Networking.epub"
Invoke-WebRequest http://ligman.me/1KBVfnS -OutFile "Microsoft System Center Extending Operations Manager Reporting.pdf"
Invoke-WebRequest http://ligman.me/1IzIbPR -OutFile "Microsoft System Center Extending Operations Manager Reporting.mobi"
Invoke-WebRequest http://ligman.me/1HBYYRF -OutFile "Microsoft System Center Extending Operations Manager Reporting.epub"
Invoke-WebRequest http://ligman.me/1IzHZA1 -OutFile "Microsoft System Center Introduction to Microsoft Automation Solutions.pdf"
Invoke-WebRequest http://ligman.me/1RWFd8K -OutFile "Microsoft System Center Introduction to Microsoft Automation Solutions.mobi"
Invoke-WebRequest http://ligman.me/1HCW4Or -OutFile "Microsoft System Center Introduction to Microsoft Automation Solutions.epub"
Invoke-WebRequest http://ligman.me/1GUUqSD -OutFile "Microsoft System Center Operations Manager Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1Cg8UQs -OutFile "Microsoft System Center Operations Manager Field Experience.mobi"
Invoke-WebRequest http://ligman.me/1KyVGkv -OutFile "Microsoft System Center Operations Manager Field Experience.epub"
Invoke-WebRequest http://ligman.me/1CQXNbj -OutFile "Microsoft System Center Software Update Management Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1M05ktI -OutFile "Microsoft System Center Software Update Management Field Experience.mobi"
Invoke-WebRequest http://ligman.me/1Ujd8fL -OutFile "Microsoft System Center Software Update Management Field Experience.epub"
Invoke-WebRequest http://ligman.me/1GUOZ6b -OutFile "Microsoft System Center Building a Virtualized Network Solution.pdf"
Invoke-WebRequest http://ligman.me/1HCR2l0 -OutFile "Microsoft System Center Building a Virtualized Network Solution.mobi"
Invoke-WebRequest http://ligman.me/1FYOjLl -OutFile "Microsoft System Center Building a Virtualized Network Solution.epub"
Invoke-WebRequest http://ligman.me/1GUP0qL -OutFile "Microsoft System Center Cloud Management with App Controller.pdf"
Invoke-WebRequest http://ligman.me/1GVyNAv -OutFile "Microsoft System Center Cloud Management with App Controller.mobi"
Invoke-WebRequest http://ligman.me/1HBSfqC -OutFile "Microsoft System Center Cloud Management with App Controller.epub"
Invoke-WebRequest http://ligman.me/1KBMN8a -OutFile "Microsoft System Center Configuration Manager Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1HCQQCb -OutFile "Microsoft System Center Configuration Manager Field Experience.mobi"
Invoke-WebRequest http://ligman.me/1Uj1dyo -OutFile "Microsoft System Center Configuration Manager Field Experience.epub"
Invoke-WebRequest http://ligman.me/1f9cKQZ -OutFile "Microsoft System Center Designing Orchestrator Runbooks.pdf"
Invoke-WebRequest http://ligman.me/1RWzUWP -OutFile "Microsoft System Center Designing Orchestrator Runbooks.mobi"
Invoke-WebRequest http://ligman.me/1LIJxJ0 -OutFile "Microsoft System Center Designing Orchestrator Runbooks.epub"
Invoke-WebRequest http://ligman.me/1gfaIzh -OutFile "Microsoft System Center Integrated Cloud Platform.pdf"
Invoke-WebRequest http://ligman.me/1LIJHA5 -OutFile "Microsoft System Center Integrated Cloud Platform.mobi"
Invoke-WebRequest http://ligman.me/1HCQXxv -OutFile "Microsoft System Center Integrated Cloud Platform.epub"
Invoke-WebRequest http://ligman.me/1JIF6vB -OutFile "Microsoft System Center Network Virtualization and Cloud Computing.pdf"
Invoke-WebRequest http://ligman.me/1TaxTZD -OutFile "Microsoft System Center Network Virtualization and Cloud Computing.mobi"
Invoke-WebRequest http://ligman.me/1TaxTJ5 -OutFile "Microsoft System Center Network Virtualization and Cloud Computing.epub"
Invoke-WebRequest http://ligman.me/1M00Lzu -OutFile "Microsoft System Center Optimizing Service Manager.pdf"
Invoke-WebRequest http://ligman.me/1Cg5xc8 -OutFile "Microsoft System Center Optimizing Service Manager.mobi"
Invoke-WebRequest http://ligman.me/1IWkjlf -OutFile "Microsoft System Center Optimizing Service Manager.epub"
Invoke-WebRequest http://ligman.me/1M00v3u -OutFile "Microsoft System Center Troubleshooting Configuration Manager.pdf"
Invoke-WebRequest http://ligman.me/1GUOMzL -OutFile "Microsoft System Center Troubleshooting Configuration Manager.mobi"
Invoke-WebRequest http://ligman.me/1TaxqXr -OutFile "Microsoft System Center Troubleshooting Configuration Manager.epub"
Invoke-WebRequest http://ligman.me/2t3NaDl -OutFile "What’s new in System Center 2016 White Paper.pdf"
Invoke-WebRequest http://ligman.me/1M05yAY -OutFile "Understanding Microsoft Virtualizaton R2 Solutions.xps"
Invoke-WebRequest http://ligman.me/1eql6Ts -OutFile "Understanding Microsoft Virtualizaton R2 Solutions.pdf"
Invoke-WebRequest http://ligman.me/2sE9XX1 -OutFile "Deploying Windows 10 Automating deployment by using System Center Configuration Manager.pdf"
Invoke-WebRequest http://ligman.me/2uZgfBj -OutFile "Deploying Windows 10 Automating deployment by using System Center Configuration Manager.mobi"
Invoke-WebRequest http://ligman.me/2tDZAUn -OutFile "Deploying Windows 10 Automating deployment by using System Center Configuration Manager.epub"
Invoke-WebRequest http://ligman.me/2twLeqF -OutFile "Deploying Windows 10 Automating deployment by using System Center Configuration Manager – Mobile.pdf"
Invoke-WebRequest http://ligman.me/2sF5tQ8 -OutFile "Getting the most out of Microsoft Edge.doc"
Invoke-WebRequest http://ligman.me/2t2WmYx -OutFile "Introducing Windows 10 for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/2uZiHI3 -OutFile "Introducing Windows 10 for IT Professionals.mobi"
Invoke-WebRequest http://ligman.me/2t2qX8T -OutFile "Introducing Windows 10 for IT Professionals.epub"
Invoke-WebRequest http://ligman.me/1Uiyx8Q -OutFile "Introducing Windows 10 for IT Professionals, Preview Edition.pdf"
Invoke-WebRequest http://ligman.me/1C6Tg9G -OutFile "Introducing Windows 10 for IT Professionals, Preview Edition.mobi"
Invoke-WebRequest http://ligman.me/1HCIlqM -OutFile "Introducing Windows 10 for IT Professionals, Preview Edition.epub"
Invoke-WebRequest http://ligman.me/1JDrMeG -OutFile "Introducing Windows 8.1 for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1GVGV3U -OutFile "Introducing Windows 8.1 for IT Professionals.mobi"
Invoke-WebRequest http://ligman.me/1JDrIvt -OutFile "Introducing Windows 8.1 for IT Professionals.epub"
Invoke-WebRequest http://ligman.me/1GVGQgI -OutFile "Introducing Windows 8 An Overview for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1RWFVCS -OutFile "Introducing Windows 8 An Overview for IT Professionals.mobi"
Invoke-WebRequest http://ligman.me/1RWFUig -OutFile "Introducing Windows 8 An Overview for IT Professionals.epub"
Invoke-WebRequest http://ligman.me/2txIfxW -OutFile "Licensing Windows desktop operating system for use with virtual machines.pdf"
Invoke-WebRequest http://ligman.me/2sVHDUg -OutFile "Protecting your data with Windows 10 BitLocker.doc"
Invoke-WebRequest http://ligman.me/2u2R83b -OutFile "RAP as a Service for Windows Desktop.pdf"
Invoke-WebRequest http://ligman.me/29ErxWs -OutFile "Shortcut Keys for Windows 10.doc"
Invoke-WebRequest http://ligman.me/29yWAAO -OutFile "Use Reset to restore your Windows 10 PC.doc"
Invoke-WebRequest http://ligman.me/2sFzkaR -OutFile "Volume Licensing Reference Guide Windows 10 Desktop Operating System.pdf"
Invoke-WebRequest http://ligman.me/2u12Nj7 -OutFile "Windows 10 IT Pro Essentials Support Secrets.pdf"
Invoke-WebRequest http://ligman.me/2uFUOG1 -OutFile "Windows 10 IT Pro Essentials Support Secrets.pdf"
Invoke-WebRequest http://ligman.me/2twRrCJ -OutFile "Windows 10 IT Pro Essentials Support Secrets.mobi"
Invoke-WebRequest http://ligman.me/2t2mx1M -OutFile "Windows 10 IT Pro Essentials Support Secrets.epub"
Invoke-WebRequest http://ligman.me/2t2cYjp -OutFile "Windows 10 IT Pro Essentials Top 10 Tools.pdf"
Invoke-WebRequest http://ligman.me/2twtAmW -OutFile "Windows 10 IT Pro Essentials Top 10 Tools.mobi"
Invoke-WebRequest http://ligman.me/2u0YnZu -OutFile "Windows 10 IT Pro Essentials Top 10 Tools.epub"
Invoke-WebRequest http://ligman.me/2u15CAR -OutFile "Windows 10 IT Pro Essentials Top 10 Tools – Mobile.pdf"
Invoke-WebRequest http://ligman.me/1sfkqBW -OutFile "Work Smart Windows 8 Shortcut Keys.pdf"
Invoke-WebRequest http://ligman.me/2txOv8Z -OutFile "Automating Windows Server 2016 configuration with PowerShell and DSC.doc"
Invoke-WebRequest http://ligman.me/1M06aXa -OutFile "Introducing Windows Server 2008 R2.xps"
Invoke-WebRequest http://ligman.me/1FYVYcy -OutFile "Introducing Windows Server 2008 R2.pdf"
Invoke-WebRequest http://ligman.me/1dDcZ5h -OutFile "Introducing Windows Server 2008 R2.mobi"
Invoke-WebRequest http://ligman.me/1H5ajbj -OutFile "Introducing Windows Server 2008 R2.epub"
Invoke-WebRequest http://ligman.me/1M0681D -OutFile "Introducing Windows Server 2012.pdf"
Invoke-WebRequest http://ligman.me/1UjeQh2 -OutFile "Introducing Windows Server 2012.mobi"
Invoke-WebRequest http://ligman.me/1JIV1Kk -OutFile "Introducing Windows Server 2012.mobi"
Invoke-WebRequest http://ligman.me/1NErPpa -OutFile "Introducing Windows Server 2012.epub"
Invoke-WebRequest http://ligman.me/1eqlNMp -OutFile "Introducing Windows Server 2012.epub"
Invoke-WebRequest http://ligman.me/1NCxHi5 -OutFile "Introducing Windows Server 2012 R2.pdf"
Invoke-WebRequest http://ligman.me/1KBX7Nw -OutFile "Introducing Windows Server 2012 R2.mobi"
Invoke-WebRequest http://ligman.me/1IzJ6Qp -OutFile "Introducing Windows Server 2012 R2.epub"
Invoke-WebRequest http://ligman.me/2uFKRZd -OutFile "Introducing Windows Server 2016.pdf"
Invoke-WebRequest http://ligman.me/2tDMJl0 -OutFile "Introducing Windows Server 2016 – Mobile.pdf"
Invoke-WebRequest http://ligman.me/2uFDelL -OutFile "Introducing Windows Server 2016 Technical Preview.pdf"
Invoke-WebRequest http://ligman.me/2twmtKY -OutFile "Introducing Windows Server 2016 Technical Preview – Mobile.pdf"
Invoke-WebRequest http://ligman.me/1f9k8fe -OutFile "Introducing Windows Server 2012 R2 Preview Release.pdf"
Invoke-WebRequest http://ligman.me/1eqm4za -OutFile "Introducing Windows Server 2012 R2 Preview Release.mobi"
Invoke-WebRequest http://ligman.me/2tXBiHF -OutFile "Introducing Windows Server 2012 R2 Preview Release.epub"
Invoke-WebRequest http://ligman.me/2v1cDyG -OutFile "Offline Assessment for Active Directory.pdf"
Invoke-WebRequest http://ligman.me/2txRQFd -OutFile "RAP as a Service for Active Directory.pdf"
Invoke-WebRequest http://ligman.me/2v1zdYa -OutFile "RAP as a Service for Failover Cluster.pdf"
Invoke-WebRequest http://ligman.me/2sW0A9v -OutFile "RAP as a Service for Internet Information Services.pdf"
Invoke-WebRequest http://ligman.me/2txQLgl -OutFile "RAP as a Service for Windows Server Hyper-V.pdf"
Invoke-WebRequest http://ligman.me/2sFbVq3 -OutFile "Windows Server 2016 Licensing.pdf"
